
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomersOrdersDataAccess
{
   
    public interface IDataSourceEntities : IDisposable
    {
        DbSet<CustomerOrder> CustomerOrders { get; set; }
        DbSet<Customer> Customers { get; set; }
        int SaveChanges();
    }


    public partial class DataSourceEntities : DbContext, IDataSourceEntities
    {
        public DataSourceEntities()
            : base("name=DataSourceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerOrder> CustomerOrders { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    }
}
